# This file may be used to create an environment using:
# $ mamba env create -f environment.yml

name: acnets
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:

  # GENERAL
  - python
  - pip
  - ipykernel
  - ipywidgets
  - flake8
  - watermark
  
  # DOC
  - quarto
  - quartodoc

  # TEST
  - pytest
  - pytest-cov
  - pytest-mpl

  # DATA
  - dvc
  - dvc-ssh
  - pandas
  - xarray
  - netcdf4
  - h5netcdf

  # VISUALIZATION
  - matplotlib
  - seaborn

  # ML
  - scikit-learn
  - shap
  # - networkx
  - py-xgboost
  - scikit-explain
  - ray-tune

  # HPO
  # - ray-tune
  # - tune-sklearn
  # - hyperopt

  # fMRI
  - pybids
  - nilearn
  
  # deep learning
  - pytorch
  # - pytorch-cuda=12.1  # optional on GPU systems
  - pytorch-lightning
  - tensorboard
  - rich
  - keras>3

  # extra fMRI tools
  # - dcm2niix
  # - heudiconv=0.8.0
  # - fmriprep-docker

  # - pip:
    # - tune-sklearn
    # - umap-learn
    # - plotly
    # - fastcluster
    # - nipype
    # - visbrain

