# This file may be used to create an environment using:
# $ conda env create --file <this file>
# platform: osx-64

name: acnets
channels:
  - conda-forge
dependencies:
  # DEV
  - python<3.11
  - dvc
  - dvc-ssh
  - ipykernel
  - ipywidgets
  - flake8
  - watermark
  - dvc
  - dvc-ssh
  # - dcm2niix
  # - heudiconv=0.8.0
  # - fmriprep-docker
  - pip
  - pip:
    # XGBoost classifier requires external libraries, don't use `xgboost` package.
    # - py-xgboost
    # UMAP requires Numba which requires numpy<=1.21.
    # - umap-learn
    - pytest
    - pytest-cov
    - pytest-plt
    - shap
    # - plotly
    - matplotlib
    - seaborn
    # - fastcluster
    - networkx
    # - nipype
    - scikit-learn
    - nilearn
    - pandas
    - xarray
    - h5netcdf
    - netCDF4
    - pybids
    - pingouin
    # - visbrain
    # - scikit-optimize
    # - tune-sklearn
    # - ray[tune]
    # - ray[data]
    # - ray
    # - pyarrow
    # - pybids

