# This file may be used to create an environment using:
# $ conda env create --file <this file>
# platform: osx-64

name: acnets
channels:
  - conda-forge
dependencies:
  # DEV
  - python=3.9
  - datalad
  - pip
  - ipykernel
  - ipywidgets
  - nbformat
  - flake8
  - pep8-naming
  - pytest
  - pytest-cov
  - watermark

  # the rest
  - plotly
  - seaborn
  - fastcluster
  - networkx
  - nipype
  - nilearn
<<<<<<< HEAD
=======

>>>>>>> master
  # there will be an incompatibility issue if it's install via pip
  - pandas
  # XGBoost classifier requires external libraries, don't use `xgboost` package.
  # - py-xgboost
  # Install XArray and its dependencies
  - xarray
  - netCDF4     # required by xarray
  # UMAP requires Numba which requires numpy<=1.21.
  - umap-learn
  - shap
<<<<<<< HEAD
=======

>>>>>>> master
  - dcm2niix
  # - heudiconv=0.8.0
  # - fmriprep-docker

  - pip:
<<<<<<< HEAD
    - pybids
    - flake8-todo
    - pytest-plt
    # - visbrain
    ## deps for hyper-parameter tuning via RayTune
    - scikit-optimize
    - tune-sklearn
    - ray[tune]
    - ray[data]
    - ray
    - pyarrow
=======
    - -r requirements.txt
>>>>>>> master
