# This file may be used to create an environment using:
# $ mamba env create -f environment.yml

name: acnets
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - ipykernel
  - ipywidgets
  - flake8
  - watermark
  - dvc
  - dvc-ssh
  - pandas
  - scikit-learn
  - nilearn
  - matplotlib
  - seaborn
  - shap
  - xarray
  - netcdf4
  - h5netcdf
  - networkx
  - py-xgboost
  - pytest
  - pytest-cov
  - pytest-mpl
  - pybids
  - ray-tune
  - tune-sklearn
  - hyperopt
  # - dcm2niix
  # - heudiconv=0.8.0
  # - fmriprep-docker
  # - pip:
    # - umap-learn
    # - plotly
    # - fastcluster
    # - nipype
    # - visbrain
    # - scikit-optimize
    # - ray[default]

