# This file may be used to create an environment using:
# $ mamba env create -f environment.yml

name: acnets
channels:
  - conda-forge

dependencies:

  # GENERAL
  - python
  - pip
  - ipykernel
  - ipywidgets
  - flake8
  - watermark

  # TEST
  - pytest
  - pytest-cov
  - pytest-mpl

  # DATA
  - dvc
  - dvc-ssh
  - pandas
  - xarray
  - netcdf4
  - h5netcdf

  # VISUALIZATION
  - matplotlib
  - seaborn

  # ML
  - scikit-learn
  - shap
  # - networkx
  - py-xgboost
  - scikit-explain

  # HPO
  # - ray-tune
  # - tune-sklearn
  # - hyperopt

  # fMRI
  - pybids
  - nilearn

  # - dcm2niix
  # - heudiconv=0.8.0
  # - fmriprep-docker

  - pip:
    - ray[tune]
    # - tune-sklearn
    # - umap-learn
    # - plotly
    # - fastcluster
    # - nipype
    # - visbrain

