# This file may be used to create an environment using:
# $ mamba env create -f environment.yml

name: multimodal
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:

  # GENERAL
  - python
  - pip
  - ipykernel
  - ipywidgets
  - flake8
  
  # DOC
  - quarto
  - quartodoc

  # TEST
  - pytest
  - pytest-cov
  - pytest-mpl

  # DATA
  - dvc
  - dvc-ssh
  - pandas
  - xarray
  - netcdf4
  - h5netcdf

  # VISUALIZATION
  - matplotlib
  - seaborn

  # ML
  - scikit-learn
  # - tsfresh  # NOTE requires older deps
  - nilearn
  
  # deep learning
  - pytorch
  - tensorboard
  - keras

  - pip:
    - pyspi
